#!/bin/bash
while getopts dt opt; do case $opt in
    d) export REJOY_DEBUG=1; opts+="-d ";;
    t) set -o xtrace; opts+="-t " ;;
esac; done; shift $((OPTIND-1))

rejoy_bin="$(readlink -f "$0")"
this_dir="$(dirname "$rejoy_bin")"
for rejoy_dir in "$rejoy_path" "$REJOY_PATH" "$this_dir" \
 "$(readlink -f "$this_dir/../share/rejoy")" "$XDG_DATA_HOME/rejoy" \
 "$HOME/.local/share/rejoy"; do if [[ -f "$rejoy_dir/funcs" ]]; then
    export rejoy_path="$rejoy_dir"; break
fi; done; unset rejoy_dir
source "$rejoy_path/funcs"
set +o monitor; shopt -s nullglob

[[ -e /etc/rejoy/conf ]] && . /etc/rejoy/conf

# If user is set to non-root, permissions will be set on rejoy's directories
# and /dev/input, and sudo will be used to switch to the new user. 
check_user

init_rejoyd
while inotifywait -qq -e close_write /run/rejoy/control; do
    source /run/rejoy/control
    echo "Received command ${cmd[@]}."
    case ${cmd[0]} in
    add)       add_joysticks ;;
    rm)        rm_joysticks ;;
    js)        process_js; reply 0 ;;
    options)   set_options "${cmd[@]:1}" ;;
    defaults)  set_defaults "${cmd[@]:1}" ;;
    reset)     reset_options ;;
    exit)      break ;;
    *)         echo "Unrecognized command." ;;
    esac
done
end_rejoyd
